// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation_Server.Data;

#nullable disable

namespace Restaurant_Reservation_API_Server.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20241124091703_ReservationDb_1")]
    partial class ReservationDb_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservation_Server.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivedTimeId")
                        .HasColumnType("int");

                    b.Property<string>("BookingDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChildSeat")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatRequirement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArrivedTimeId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Restaurant_Reservation_API_Server.Models.ArrivedTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("arrivedTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Period = "11:30"
                        },
                        new
                        {
                            Id = 2,
                            Period = "13:30"
                        },
                        new
                        {
                            Id = 3,
                            Period = "15:30"
                        },
                        new
                        {
                            Id = 4,
                            Period = "17:30"
                        },
                        new
                        {
                            Id = 5,
                            Period = "19:30"
                        });
                });

            modelBuilder.Entity("Reservation_Server.Models.Reservation", b =>
                {
                    b.HasOne("Restaurant_Reservation_API_Server.Models.ArrivedTime", "ArrivedTime")
                        .WithMany()
                        .HasForeignKey("ArrivedTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivedTime");
                });
#pragma warning restore 612, 618
        }
    }
}
